spring:
  datasource:
    url: jdbc:mariadb://board.c7wdhtetojg1.ap-northeast-2.rds.amazonaws.com:3306/board # jdbc:h2:tcp://localhost/~/board
    username: # sa
    password:
    driver-class-name: org.mariadb.jdbc.Driver # org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true #운영 시에는 주석처리
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug